server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-service:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /parking/ {
        proxy_pass http://parking-service:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        default_type application/json;
        return 404 '{"message":"Route not found"}';
    }
}
